### PR TITLE
Fix edit/delete command to include band list

### LINKED ISSUE #127: Fix edit/delete command to include band list
Currently, operations on musicians are not synced to the bands since
1. Bands do not store a reference to the musician
2. Editing a musician involves deleting the old object and insert a new object, deleting a musicians involves deleting the old object.

We should fix this bug and make sure that every operation performed on musicians be promptly reflected on bands as well.

### PR DESCRIPTION
**Pull request by leawang0**
This PR contains the necessary fixes so that edits/deletes made to the musician is promptly reflected in all bands that the musician belongs to.

**Rationale:**
Currently, operations on musicians are not synced to the bands since 
1. Bands do not store a reference to the musician
2. Editing a musician involves deleting the old object and insert a new object, deleting a musicians involves deleting the old object.

Due to the above reasons, there is a need to separately update the band list (loop over all bands and edit/delete the corresponding musician) while doing edit/delete operation for musician.

**Implementation:**
- In `ModelManager`, both `filteredmusicians` and `filteredbands` are set to display all musicians/bands. This is to ensure deterministic and consistent behaviours for UI. 
- In `ModelManager`, a `updateMusicianInAllBands(Musician target, Musician editedMusician)` is created to loop through all bands and do the changes.

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -100,18 +100,38 @@ public boolean hasMusician(Musician musician) {
...
+        updateFilteredBandList(Model.PREDICATE_SHOW_ALL_BANDS);
     }
 
     @Override
     public void setMusician(Musician target, Musician editedMusician) {
         requireAllNonNull(target, editedMusician);
         addressBook.setMusician(target, editedMusician);
+
+        updateFilteredMusicianList(PREDICATE_SHOW_ALL_MUSICIANS);
+        updateFilteredBandList(PREDICATE_SHOW_ALL_BANDS);
```
Comment (tanyyyming) [inline src/main/java/seedu/address/model/ModelManager.java:123]: I see the rationale here. This is to jump back to the state where all the musicians and bands are listed to avoid any inconsistency and confusion for the user. Though this might not be the optimal solution, I think this is the best we can have right now.

File: src/test/java/seedu/address/logic/commands/AddMusicianToBandCommandTest.java [hunk 2]
```diff
@@ -244,6 +244,9 @@ public ObservableList<Band> getFilteredBandList() {
             return new FilteredList<>(bandsAdded.asUnmodifiableObservableList());
         }
         @Override
+        public void updateFilteredBandList(Predicate<Band> predicate) {
+        }
```
Comment (tanyyyming) [inline src/test/java/seedu/address/logic/commands/AddMusicianToBandCommandTest.java:248]: Is this a stub? Just to confirm lol.

**Review by tanyyyming — APPROVED** [review]
LGTM overall! Thanks for making the command result more consistent and less confusing to the user!
